name: demo-onedata 
channels:
- conda-forge
dependencies:
- python
- xarray
- numpy
- scipy
- matplotlib
- cartopy
- xarray
- xlrd
- pip
- pip:
  - git+https://github.com/EGI-Foundation/egi-notebooks-addons
  - git+https://github.com/enolfc/fs-onedatafs.git@notebooks
  - git+https://github.com/enolfc/onedatafs.git@19.02.0-rc2
  - git+https://github.com/onedata/onedatafs-jupyter.git
